---
# tasks file for commons
#Tarefa para configurar TimeZone

- name: Configurando TimeZone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

#Utilizando o Modulo Copy

- name: Copiando arquivo com o Modulo Copy
  copy: src=alan.txt dest=/tmp/alan-copy.txt

#Utilizando um template

- name: Copiando o template motd
  template: src=motd dest=/etc/motd force=yes owner=root group=root

#Utilizando um Handler

- name: Install Nginx
  apt: name=nginx state=present
  notify: Restart Nginx
  when: ansible_distribution == "Debian"
...
